// The quant scan is generated by `python -m quant.scan` and mirrored to
// data/scan.json, which we import statically so Vercel bundles the latest scan
// at build time — no DB round-trip needed to render the dashboard.
import scanData from "@/data/scan.json";

export type Label = "STRONG_BUY" | "BUY" | "NEUTRAL" | "SELL" | "STRONG_SELL";

export interface Component {
  score: number;
  weight: number;
  reason: string;
}

export interface Trade {
  direction: "long" | "short";
  entry: number;
  stop: number;
  target: number;
  risk_per_share: number;
  reward_per_share: number;
  risk_reward: number;
  actionable: boolean;
  note: string;
}

export interface Calibration {
  band: Label;
  hit_rate_15d: number | null;
  alpha_15d_pct: number | null;
  samples: number | null;
  oos_hit_rate_15d: number | null;
  oos_alpha_15d_pct: number | null;
}

export interface ExpectedLeg {
  sigma_pct: number;
  low: number;
  high: number;
}

export interface Signal {
  symbol: string;
  market: string;
  sector: string;
  as_of: string;
  last_close: number;
  score: number;
  label: Label;
  core: number;
  conviction: number;
  components: Record<string, Component>;
  timing: { adjustment: number; reason: string };
  volatility: { atr_14: number; atr_pct: number; daily_vol_pct: number; annual_vol_pct: number };
  expected_move: { "5d": ExpectedLeg; "15d": ExpectedLeg; "30d": ExpectedLeg };
  key_levels: { support: number[]; resistance: number[] };
  trade: Trade | null;
  calibration: Calibration;
  is_favourite: boolean;
}

export interface Scan {
  as_of: string;
  universe_size: number;
  backtest_meta: {
    samples: number;
    symbols: number;
    date_range: [string, string];
    oos_split: string;
    horizons: number[];
    step_days: number;
    long_short_edge_15d_pct: number | null;
    note: string;
    by_market: Record<string, { long_short_edge_15d_pct: number | null; samples: number; symbols: number }>;
  };
  favourites: string[];
  signals: Signal[];
}

export type MarketFilter = "All" | "US" | "India";

/** Native currency symbol per market — keeps $295 and ₹1,269 unambiguous. */
export function currencyFor(market: string): string {
  return market === "India" ? "₹" : "$";
}

export function fmtPrice(market: string, value: number): string {
  return `${currencyFor(market)}${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

const inMarket = (m: MarketFilter) => (s: Signal) => m === "All" || s.market === m;

export const scan = scanData as unknown as Scan;

export function getSignal(symbol: string): Signal | undefined {
  return scan.signals.find((s) => s.symbol === symbol);
}

const isLong = (s: Signal) => s.label === "STRONG_BUY" || s.label === "BUY";
const isShort = (s: Signal) => s.label === "STRONG_SELL" || s.label === "SELL";

/** Strongest longs in the selected market, highest score first. */
export function topLongs(market: MarketFilter = "All", n = 6): Signal[] {
  return scan.signals.filter(inMarket(market)).filter(isLong).sort((a, b) => b.score - a.score).slice(0, n);
}

/** Strongest shorts in the selected market, lowest score first. */
export function topShorts(market: MarketFilter = "All", n = 6): Signal[] {
  return scan.signals.filter(inMarket(market)).filter(isShort).sort((a, b) => a.score - b.score).slice(0, n);
}

export function favourites(market: MarketFilter = "All"): Signal[] {
  return scan.signals
    .filter(inMarket(market))
    .filter((s) => s.is_favourite)
    .sort((a, b) => b.conviction - a.conviction);
}

/** The "book": net bias for the selected market. */
export function book(market: MarketFilter = "All") {
  const set = scan.signals.filter(inMarket(market));
  const longs = set.filter(isLong).length;
  const shorts = set.filter(isShort).length;
  const actionable = set.filter((s) => s.trade?.actionable).length;
  return { longs, shorts, neutral: set.length - longs - shorts, actionable, total: set.length };
}

/** Backtested long/short alpha edge for the selected market (or blended for "All"). */
export function edgeFor(market: MarketFilter): number | null {
  if (market === "All") return scan.backtest_meta.long_short_edge_15d_pct;
  return scan.backtest_meta.by_market?.[market]?.long_short_edge_15d_pct ?? null;
}
