// The quant scan is generated by `python -m quant.scan` and mirrored to
// data/scan.json, which we import statically so Vercel bundles the latest scan
// at build time — no DB round-trip needed to render the dashboard.
import scanData from "@/data/scan.json";

export type Label = "STRONG_BUY" | "BUY" | "NEUTRAL" | "SELL" | "STRONG_SELL";

export interface Component {
  score: number;
  weight: number;
  reason: string;
}

export interface Trade {
  direction: "long" | "short";
  entry: number;
  stop: number;
  target: number;
  risk_per_share: number;
  reward_per_share: number;
  risk_reward: number;
  actionable: boolean;
  note: string;
}

export interface Calibration {
  band: Label;
  market: string;
  tradeable: boolean;
  reason: string;
  win_rate: number | null;       // rule-based, out-of-sample
  expectancy_pct: number | null; // net per-trade, out-of-sample
  profit_factor: number | null;
  samples: number | null;
  avg_hold_days: number | null;
}

export interface ExpectedLeg {
  sigma_pct: number;
  low: number;
  high: number;
}

export interface Signal {
  symbol: string;
  market: string;
  sector: string;
  as_of: string;
  last_close: number;
  score: number;
  label: Label;
  core: number;
  conviction: number;
  components: Record<string, Component>;
  timing: { adjustment: number; reason: string };
  volatility: { atr_14: number; atr_pct: number; daily_vol_pct: number; annual_vol_pct: number };
  expected_move: { "5d": ExpectedLeg; "15d": ExpectedLeg; "30d": ExpectedLeg };
  key_levels: { support: number[]; resistance: number[] };
  trade: Trade | null;
  calibration: Calibration;
  quality: Quality | null;
  events: Events | null;
  narration: Narration | null;
  history: PricePoint[];
  is_favourite: boolean;
}

export interface Narration {
  thesis: string | null;
  caution: string | null;
}

export interface Quality {
  score: number;
  assessment: "CHEAP" | "FAIR" | "EXPENSIVE";
  components: Record<string, { score: number; reason: string }>;
  reasons: string[];
}

export interface Events {
  next_earnings_date: string | null;
  days_to_earnings: number | null;
  event_within_horizon: boolean;
  flag: "EARNINGS_SOON" | "CLEAR";
}

export interface Macro {
  regime: "EASING" | "NEUTRAL" | "TIGHTENING";
  policy_rate: number | null;
  ten_year: number | null;
  curve_slope_bps: number | null;
  fx: { pair: string; level: number; trend: string } | null;
  as_of: string;
  source: string;
}

export interface PricePoint {
  d: string;       // date
  c: number;       // close
  m: number | null; // 50-day SMA
}

export interface Scan {
  as_of: string;
  universe_size: number;
  evidence: {
    us_long_oos: {
      win_rate: number | null;
      expectancy_pct: number | null;
      profit_factor: number | null;
      trades: number | null;
    };
    portfolio: CurveStats;
    benchmark: CurveStats;
    rule: string | null;
    date_range: [string, string] | null;
    caveats: string;
  };
  macro: Record<string, Macro | null>;
  favourites: string[];
  signals: Signal[];
}

export interface CurveStats {
  label?: string;
  total_return_pct?: number;
  cagr_pct?: number;
  vol_pct?: number;
  sharpe?: number | null;
  max_drawdown_pct?: number;
}

export type MarketFilter = "All" | "US" | "India";

/** Native currency symbol per market — keeps $295 and ₹1,269 unambiguous. */
export function currencyFor(market: string): string {
  return market === "India" ? "₹" : "$";
}

export function fmtPrice(market: string, value: number): string {
  return `${currencyFor(market)}${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

const inMarket = (m: MarketFilter) => (s: Signal) => m === "All" || s.market === m;

export const scan = scanData as unknown as Scan;

export function getSignal(symbol: string): Signal | undefined {
  return scan.signals.find((s) => s.symbol === symbol);
}

const isLong = (s: Signal) => s.label === "STRONG_BUY" || s.label === "BUY";
const isShort = (s: Signal) => s.label === "STRONG_SELL" || s.label === "SELL";

/** Strongest longs in the selected market, highest score first. */
export function topLongs(market: MarketFilter = "All", n = 6): Signal[] {
  return scan.signals.filter(inMarket(market)).filter(isLong).sort((a, b) => b.score - a.score).slice(0, n);
}

/** Strongest shorts in the selected market, lowest score first. */
export function topShorts(market: MarketFilter = "All", n = 6): Signal[] {
  return scan.signals.filter(inMarket(market)).filter(isShort).sort((a, b) => a.score - b.score).slice(0, n);
}

/** Tradeable signals (US longs that cleared the backtest), highest score first. */
export function tradeable(market: MarketFilter = "All"): Signal[] {
  return scan.signals
    .filter(inMarket(market))
    .filter((s) => s.calibration.tradeable)
    .sort((a, b) => b.score - a.score);
}

/** Informational signals (no validated edge) — shorts + India — by conviction. */
export function informational(market: MarketFilter = "All"): Signal[] {
  return scan.signals
    .filter(inMarket(market))
    .filter((s) => !s.calibration.tradeable && s.label !== "NEUTRAL")
    .sort((a, b) => b.conviction - a.conviction);
}

export function getSignalsBySymbols(symbols: string[]): Signal[] {
  return symbols.map((s) => getSignal(s)).filter(Boolean) as Signal[];
}

/** The "book": net bias for the selected market. */
export function book(market: MarketFilter = "All") {
  const set = scan.signals.filter(inMarket(market));
  const longs = set.filter(isLong).length;
  const shorts = set.filter(isShort).length;
  const td = set.filter((s) => s.calibration.tradeable).length;
  return { longs, shorts, neutral: set.length - longs - shorts, tradeable: td, total: set.length };
}
