// The quant scan is generated by `python -m quant.scan` and mirrored to
// data/scan.json, which we import statically so Vercel bundles the latest scan
// at build time — no DB round-trip needed to render the dashboard.
import scanData from "@/data/scan.json";

export type Label = "STRONG_BUY" | "BUY" | "NEUTRAL" | "SELL" | "STRONG_SELL";

export interface Component {
  score: number;
  weight: number;
  reason: string;
}

export interface Trade {
  direction: "long" | "short";
  entry: number;
  stop: number;
  target: number;
  risk_per_share: number;
  reward_per_share: number;
  risk_reward: number;
  actionable: boolean;
  note: string;
}

export interface Calibration {
  band: Label;
  hit_rate_15d: number | null;
  alpha_15d_pct: number | null;
  samples: number | null;
  oos_hit_rate_15d: number | null;
  oos_alpha_15d_pct: number | null;
}

export interface ExpectedLeg {
  sigma_pct: number;
  low: number;
  high: number;
}

export interface Signal {
  symbol: string;
  market: string;
  sector: string;
  as_of: string;
  last_close: number;
  score: number;
  label: Label;
  core: number;
  conviction: number;
  components: Record<string, Component>;
  timing: { adjustment: number; reason: string };
  volatility: { atr_14: number; atr_pct: number; daily_vol_pct: number; annual_vol_pct: number };
  expected_move: { "5d": ExpectedLeg; "15d": ExpectedLeg; "30d": ExpectedLeg };
  key_levels: { support: number[]; resistance: number[] };
  trade: Trade | null;
  calibration: Calibration;
  is_favourite: boolean;
}

export interface Scan {
  as_of: string;
  universe_size: number;
  backtest_meta: {
    samples: number;
    symbols: number;
    date_range: [string, string];
    oos_split: string;
    horizons: number[];
    step_days: number;
    long_short_edge_15d_pct: number | null;
    note: string;
  };
  favourites: string[];
  signals: Signal[];
}

export const scan = scanData as unknown as Scan;

export function getSignal(symbol: string): Signal | undefined {
  return scan.signals.find((s) => s.symbol === symbol);
}

const isLong = (s: Signal) => s.label === "STRONG_BUY" || s.label === "BUY";
const isShort = (s: Signal) => s.label === "STRONG_SELL" || s.label === "SELL";

/** Strongest longs, highest score first. */
export function topLongs(n = 6): Signal[] {
  return scan.signals.filter(isLong).sort((a, b) => b.score - a.score).slice(0, n);
}

/** Strongest shorts, lowest score first. */
export function topShorts(n = 6): Signal[] {
  return scan.signals.filter(isShort).sort((a, b) => a.score - b.score).slice(0, n);
}

export function favourites(): Signal[] {
  return scan.signals
    .filter((s) => s.is_favourite)
    .sort((a, b) => b.conviction - a.conviction);
}

/** The "book": net bias + sector/market mix for the scanned universe. */
export function book() {
  const longs = scan.signals.filter(isLong).length;
  const shorts = scan.signals.filter(isShort).length;
  const neutral = scan.signals.length - longs - shorts;
  const actionable = scan.signals.filter((s) => s.trade?.actionable).length;
  return { longs, shorts, neutral, actionable, total: scan.signals.length };
}
